### ISSUE TITLE
Error Enabling ChatTools

### ISSUE THREAD

**Issue by MorroZ** [JGSBroadcast/ChatTools#1]
Hello There,

So i Enabled ChatTools via plugman for testing issues and there we go, a error in my console.

http://pastebin.com/ieTE28is

Is it more something from Plugman?

**Comment by JGSBroadcast** [comment]
It looks as if there already is a permission called "ct.*" in another plugin or perhaps in Plugman(I've never heard or used it before so I wouldn't know)

**Comment by JGSBroadcast** [comment]
You shouldn't get anymore errors as of v2.0. For some reason Plugman didn't like that I registered the permissions.
